# Generated by Django 5.0.6 on 2024-05-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsapi', '0002_userpassword_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpassword',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
